
name: Test deployment

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install typst
        uses: typst-community/setup-typst@v4
        with:
          typst-version: 'v0.13.1'

      - name: Install dependencies
        run: npm ci
      - name: Generate Docs
        run: npm run generate-docs
      - name: Generate Typst images
        run: npm run generate-images
      - name: Test build website
        run: npm run build